version: '3'
services:
  mysql:
    image: mysql:8.4.0
    container_name: monitor_mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor
      MYSQL_DATABASE: monitor
    hostname: monitor_mysql.org
  zookeeper:
    container_name: monitor_zookeeper
    image: zookeeper:3.9.2
    ports:
      - "2183:2181"
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=*
    hostname: monitor_zookeeper.org
  kafka:
    container_name: monitor_kafka
    image: bitnami/kafka:3.7.0
    hostname: monitor_kafka.org
    ports:
      - 9095:9095
      - 9096:9096
    environment:
      # BITNAMI_DEBUG: yes
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9095,CONTROLLER://0.0.0.0:9096
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      KAFKA_CFG_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9096
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
  redis:
    container_name: monitor_redis
    image: redis:7.2.4
    command:
          redis-server --save 60 1
    ports:
      - "6381:6379"
    hostname: monitor_redis.org
