logging:
  config: classpath:logback.xml

profile: dev

server:
  port: 8091
  address: 0.0.0.0
spring:
#  aop:
#    auto: false
#    proxy-target-class: false
  r2dbc:
    url: r2dbcs:mysql://localhost:3309/monitor?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: monitor
    password: monitor
#  flyway:
#    baseline-description: monitor migration
#    baseline-on-migrate: true
#    url: jdbc:mysql://docker.korov.online:3309/monitor?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    user: monitor
#    password: monitor
#    locations: classpath:dev/migration/mysql,classpath:db/migration/mysql
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    database-change-log-lock-table: monitor-liquibase-log-lock
    database-change-log-table: monitor-liquibase-log
    url: jdbc:mysql://localhost:3309/monitor?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    user: monitor
    password: monitor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

